# Generated by Django 4.2 on 2023-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("uz", "Uzbek"), ("en", "English"), ("ru", "Russian")],
                default="uz",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("super_user", "Super User"), ("user", "User")],
                default="user",
                max_length=65,
            ),
        ),
    ]
