# Generated by Django 4.2 on 2023-04-24 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_language_alter_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
