# Generated by Django 4.2 on 2023-05-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("super_user", "super_user"), ("user", "user")],
                default="user",
                max_length=65,
            ),
        ),
    ]
