# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0002_alter_bankcard_card_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcard",
            name="is_deleted",
        ),
    ]
