# Generated by Django 4.2 on 2023-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0003_remove_bankcard_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="card_number",
            field=models.CharField(verbose_name="card number"),
        ),
    ]
