# Generated by Django 4.2 on 2023-04-18 08:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100, verbose_name="type")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="phone"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "bank_name",
                    models.CharField(max_length=150, verbose_name="bank name"),
                ),
                ("mfo", models.IntegerField(verbose_name="mfo")),
                (
                    "bank_account",
                    models.CharField(max_length=50, verbose_name="bank account"),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
