# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="is_deleted",
        ),
    ]
