# Generated by Django 4.2 on 2023-04-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="buyers.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="bankcard",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_cards",
                to="buyers.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to="buyers.buyer",
            ),
        ),
    ]
