# Generated by Django 4.2 on 2023-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0002_alter_address_buyer_alter_bankcard_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="card_number",
            field=models.CharField(unique=True, verbose_name="card number"),
        ),
    ]
