# Generated by Django 4.2 on 2023-04-25 06:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0003_alter_bankcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="card_number",
            field=models.CharField(verbose_name="card number"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="phone number"
            ),
        ),
    ]
