# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0004_alter_bankcard_card_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="bankcard",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="phonenumber",
            name="is_deleted",
        ),
    ]
