# Generated by Django 4.2 on 2023-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_remove_address_is_deleted_remove_bankcard_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(max_length=255, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_month',
            field=models.CharField(max_length=255, verbose_name='expiry month'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_year',
            field=models.CharField(max_length=255, verbose_name='expiry year'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='middle name'),
        ),
    ]
