# Generated by Django 4.2 on 2023-04-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="company name"),
                ),
                ("inn", models.CharField(max_length=50, verbose_name="inn")),
                (
                    "bank_name",
                    models.CharField(max_length=150, verbose_name="bank name"),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=50, verbose_name="bank account"),
                ),
                ("mfo", models.IntegerField(verbose_name="mfo")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
