# Generated by Django 4.2 on 2023-05-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customer"),
        ("settings", "0002_remove_settings_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="users.customer",
            ),
        ),
    ]
