# Generated by Django 4.2 on 2023-04-26 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="DocFile",
        ),
        migrations.AlterModelOptions(
            name="docfile",
            options={
                "ordering": ("-id",),
                "verbose_name": "doc_file",
                "verbose_name_plural": "doc_files",
            },
        ),
    ]
