# Generated by Django 4.2 on 2023-04-26 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
        ("images", "0002_rename_image_docfile_alter_docfile_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocFile",
            new_name="Image",
        ),
    ]
