# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_rename_docfile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="is_deleted",
        ),
    ]
