# Generated by Django 4.2 on 2023-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="images/%Y/%m/%d/"),
        ),
    ]
