# Generated by Django 4.2 on 2023-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="address")),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="company name"),
                ),
                ("inn", models.CharField(max_length=50, verbose_name="inn")),
                ("bank_name", models.CharField(verbose_name="bank name")),
                (
                    "bank_account",
                    models.CharField(max_length=50, verbose_name="bank account"),
                ),
                ("mfo", models.CharField(max_length=20, verbose_name="mfo")),
            ],
            options={
                "db_table": "companies",
                "ordering": ("-id",),
            },
        ),
    ]
