# Generated by Django 4.2 on 2023-04-26 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="companyname",
            table=None,
        ),
    ]
