# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_companyname_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyname",
            name="is_deleted",
        ),
    ]
