# Generated by Django 4.2 on 2023-04-28 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0002_remove_merchant_is_deleted"),
        ("products", "0003_remove_category_is_deleted_remove_product_is_deleted"),
        (
            "buyers",
            "0005_remove_address_is_deleted_remove_bankcard_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bought_date", models.DateTimeField(verbose_name="bought date")),
                ("interval", models.IntegerField(verbose_name="interval")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                (
                    "payment_date",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="payment date",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="total price"
                    ),
                ),
                (
                    "first_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="first payment"
                    ),
                ),
                (
                    "left_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="left payment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default=("Open", "Open"),
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="buyer_order",
                        to="buyers.buyer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="amount"
                    ),
                ),
                (
                    "bank_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment_bank_card",
                        to="buyers.bankcard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(max_length=50, verbose_name="serial number"),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_by", models.IntegerField(verbose_name="order by")),
                ("date", models.DateTimeField(verbose_name="date")),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="monthly payment"
                    ),
                ),
                (
                    "remained_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="remained payment"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
