# Generated by Django 4.2 on 2023-05-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bought_date",
            field=models.DateTimeField(blank=True, verbose_name="bought date"),
        ),
    ]
