# Generated by Django 4.2 on 2023-05-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_bought_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bought_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="bought date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end date"),
        ),
    ]
