# Generated by Django 4.2 on 2023-05-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_bought_date_alter_order_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("OPENED", "OPENED"), ("CLOSED", "CLOSED")],
                default=("OPENED", "OPENED"),
                verbose_name="status",
            ),
        ),
    ]
