# Generated by Django 4.2 on 2023-05-01 07:16

from django.db import migrations
import django_enumfield.db.fields
import utility.enums


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=django_enumfield.db.fields.EnumField(
                default=1, enum=utility.enums.StatusEnum
            ),
        ),
    ]
