# Generated by Django 4.2 on 2023-04-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial_number", models.CharField(verbose_name="serial number")),
                ("name", models.CharField(verbose_name="name")),
                ("company", models.CharField(max_length=128, verbose_name="company")),
                (
                    "image",
                    models.ImageField(
                        upload_to="product-images/", verbose_name="image"
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="model")),
                ("iclg", models.CharField(max_length=128, verbose_name="iclg")),
                ("color", models.CharField(max_length=128, verbose_name="color")),
                ("country", models.CharField(max_length=128, verbose_name="country")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="price"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_product",
                        to="products.category",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_merchant",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
