# Generated by Django 4.2 on 2023-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_is_deleted_remove_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='serial number'),
        ),
    ]
